version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

#clash_rule_base = "base/aws_all.yml"

[[custom_groups]]
name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]ğŸ‡­ğŸ‡° é¦™æ¸¯-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡°ğŸ‡· éŸ©å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡ºğŸ‡² ç¾å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsVIAcdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv4-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv6-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "ğŸš€ æ‰‹åŠ¨åˆ‡æ¢"
type = "select"
rule = [".*", "!!PROVIDER=aws", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "ğŸ–¥ï¸ parsec"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡°ğŸ‡· éŸ©å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡ºğŸ‡² ç¾å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsVIAcdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv4-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv6-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", ".*", "!!PROVIDER=aws", "[]REJECT"]

[[custom_groups]]
name = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡°ğŸ‡· éŸ©å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡ºğŸ‡² ç¾å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsVIAcdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv4-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv6-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", ".*", "!!PROVIDER=aws", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "ğŸ“¢ è°·æ­Œæ¨é€"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡°ğŸ‡· éŸ©å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡ºğŸ‡² ç¾å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsVIAcdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv4-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv6-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", ".*", "!!PROVIDER=aws", "[]REJECT"]

[[custom_groups]]
name = "ğŸ¥ å¥ˆé£è§£é”"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡°ğŸ‡· éŸ©å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡ºğŸ‡² ç¾å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsVIAcdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv4-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv6-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", ".*", "!!PROVIDER=aws", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "ğŸ“º æ²¹ç®¡è§†é¢‘"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡°ğŸ‡· éŸ©å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡ºğŸ‡² ç¾å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsVIAcdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv4-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv6-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", ".*", "!!PROVIDER=aws", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡°ğŸ‡· éŸ©å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡ºğŸ‡² ç¾å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsVIAcdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv4-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv6-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", ".*", "!!PROVIDER=aws", "[]REJECT"]

[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
type = "select"
rule = ["[]DIRECT", "[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡°ğŸ‡· éŸ©å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡ºğŸ‡² ç¾å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsVIAcdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv4-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv6-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", ".*", "!!PROVIDER=aws", "[]REJECT"]

[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
type = "select"
rule = ["[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©", "[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡­ğŸ‡° é¦™æ¸¯-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¨ğŸ‡³ å°æ¹¾-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡°ğŸ‡· éŸ©å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡ºğŸ‡² ç¾å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ aws-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsVIAcdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ ec2-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ lightsail-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv4-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸ‡¸ğŸ‡¬ awsv6-è´Ÿè½½å‡è¡¡-è½®è¯¢", "[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢", ".*", "!!PROVIDER=aws", "[]DIRECT", "[]REJECT"]

[[custom_groups]]
name = "ğŸ‡­ğŸ‡° é¦™æ¸¯-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["(æ¸¯|HK|Hong Kong)"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¯ğŸ‡µ æ—¥æœ¬-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan)"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡°ğŸ‡· éŸ©å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["(KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“)"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡ºğŸ‡² ç¾å›½-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States)"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å°æ¹¾-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ aws-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["!!PROVIDER=lb-aws"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ aws-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["!!PROVIDER=lb-ec2-nocdn", "!!PROVIDER=lb-lightsail-nocdn"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ awsVIAcdn-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["!!PROVIDER=lb-aws-cdn"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ ec2-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["!!PROVIDER=lb-ec2"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ lightsail-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["!!PROVIDER=lb-lightsail"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ ec2-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["!!PROVIDER=lb-ec2-nocdn"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ lightsail-nocdn-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["!!PROVIDER=lb-lightsail-nocdn"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ awsv4-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["!!PROVIDER=lb-awsv4"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ awsv6-è´Ÿè½½å‡è¡¡-è½®è¯¢"
type = "load-balance"
rule = ["!!PROVIDER=lb-awsv6"]
interval = 100
strategy = "round-robin"
url = "http://www.gstatic.com/generate_204"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ericsyj/clash_rule/main/global_direct.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ericsyj/clash_rule/main/proxy.list"

[[rulesets]]
group = "ğŸ–¥ï¸ parsec"
ruleset = "https://raw.githubusercontent.com/ericsyj/clash_rule/main/parsec.list"

[[rulesets]]
group = "ğŸ“¢ è°·æ­Œæ¨é€"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list"

[[rulesets]]
group = "ğŸ¥ å¥ˆé£è§£é”"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/Netflix.list"

[[rulesets]]
group = "ğŸ“º æ²¹ç®¡è§†é¢‘"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Global-Services/YouTube.list"

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Microsoft.list"

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/Apple.list"

[[rulesets]]
group = "ğŸ“² ç”µæŠ¥æ¶ˆæ¯"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"

[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "https://raw.githubusercontent.com/LM-Firefly/Rules/master/GlobalMedia.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
